In [2]:
import cv2 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
image = cv2.imread("lena.jpg",0)
# image = cv2.imread("../Resource/lena.jpg",1)
# image = cv2.imread("../Resource/lena.jpg",-1)

print(image)
cv2.imshow("Lena" , image)
# cv2.waitKey(8000)
if cv2.waitKey(0) == 27: # Escape key
    
    cv2.destroyAllWindows()
    
elif cv2.waitKey(0) == ord('s'): # Save
    
    cv2.imwrite("Lena_Copy.png",image)
    cv2.destroyAllWindows()

[[163 162 161 ... 170 154 130]
 [162 162 162 ... 173 155 126]
 [162 162 163 ... 170 155 128]
 ...
 [ 43  42  51 ... 103 101  99]
 [ 41  42  55 ... 103 105 106]
 [ 42  44  57 ... 102 106 109]]
