In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
# test difference between read as grayscale and convert grascale 
img1 = cv2.imread("Orange1.jpg" , 0)
img2 = cv2.imread("Orange1.jpg" , 1)
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)


cv2.imshow("Orange1",img1)
cv2.imshow("Orange2",img2)
cv2.imshow("Orange2gray",img2_gray)

cv2.waitKey(0)
cv2.destroyAllWindows()

#### What are contours?
---

- Contours can be explained simply as a curve joining all the continuous points (along the boundary), having same color or intensity. The contours are a useful tool for shape analysis and object detection and recognition.

    - For better accuracy, use binary images. So before finding contours, apply threshold or canny edge detection.
    - Since OpenCV 3.2, findContours() no longer modifies the source image.
    - In OpenCV, finding contours is like finding white object from black background. So remember, object to be found should be white and background should be black.

[Contours : Getting Started | official docs](https://docs.opencv.org/4.x/d4/d73/tutorial_py_contours_begin.html)

In [9]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
# for contours binary image is best
img = cv2.imread("logo.jpg" , 1)
imgray = cv2.imread("logo.jpg" , 0)

ret, thresh = cv2.threshold(imgray, 127, 255, 0)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
# check docstring
print("Number of contours = " + str(len(contours)))
print(contours[0])

cv2.drawContours(img, contours, 2, (0, 255, 0), 3) # 3 is thickness
cv2.drawContours(imgray, contours, -1, (0, 255, 0), 3)
# -1 means draw all contours 

cv2.imshow("logo1",img)
cv2.imshow("logoGray",imgray)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contours = 4
[[[0 0]]

 [[0 1]]

 [[0 2]]

 ...

 [[3 0]]

 [[2 0]]

 [[1 0]]]
