In [1]:
import numpy as np
import cv2

In [2]:
import cv2

input = cv2.imread("imran.jpg")

cv2.imshow("imran" , input)
cv2.waitKey(0)

cv2.destroyAllWindows()

### Face Detect

In [3]:
# Load our image then convert it to grayscale
image = cv2.imread('imran.jpg')
print(image) 

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 41  33  34]
  [ 41  33  34]
  [ 41  33  34]
  ...
  [ 44  26  79]
  [ 46  26  79]
  [ 53  33  86]]

 [[ 41  33  34]
  [ 41  33  34]
  [ 41  33  34]
  ...
  [ 42  24  77]
  [ 44  24  77]
  [ 50  31  82]]

 [[ 41  33  34]
  [ 41  33  34]
  [ 41  33  34]
  ...
  [ 40  22  75]
  [ 42  23  74]
  [ 48  29  80]]]


In [4]:
print(image.shape)

(720, 1280, 3)


In [5]:
# harr face classifier (XML file format) is stored
face_classifier = cv2.CascadeClassifier('data/haarcascades/haarcascade_frontalface_default.xml')
print(face_classifier)

<CascadeClassifier 0x7eff8bb8dcb0>


In [7]:
# Load our image then convert it to grayscale
image = cv2.imread('imran.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print(gray.shape)

(720, 1280)


In [8]:
print(gray)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [ 34  34  34 ...  44  44  51]
 [ 34  34  34 ...  42  42  48]
 [ 34  34  34 ...  40  40  46]]


In [13]:
cv2.imwrite('grayTrump.jpg', gray)

True

cv  ::  CascadeClassifier  ::  detectMultiScale to perform the detection.

In [9]:
# Our classifier returns the ROI of the detected face as a tuple
# It stores the top left coordinate and the bottom right coordiantes
faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No faces found")

# We iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (255,0,0), 2)
    cv2.imshow('Face Detection', image)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
/tmp/ipykernel_24582/488435043.py:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


### Eye and face detection

In [12]:
import numpy as np
import cv2
 
face_classifier = cv2.CascadeClassifier('data/haarcascades/haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('data/haarcascades/haarcascade_eye.xml')
 
img = cv2.imread('Trump.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No Face Found")

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(127,0,255),2)
    cv2.imshow('img',img)
    cv2.waitKey(0)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(255,255,0),2)
        cv2.imshow('img',img)
        cv2.waitKey(0)
    
cv2.destroyAllWindows()

<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
/tmp/ipykernel_24582/3353765363.py:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():
